-- Crear la base de datos
CREATE DATABASE IF NOT EXISTS demo_jpa_one2one;
USE demo_jpa_one2one;

-- Crear tabla 'persona'
CREATE TABLE persona (
                         id BIGINT AUTO_INCREMENT PRIMARY KEY,
                         nombre VARCHAR(100) NOT NULL
);

-- Crear tabla 'documento'
CREATE TABLE documento (
                           id BIGINT AUTO_INCREMENT PRIMARY KEY,
                           tipo VARCHAR(50) NOT NULL,
                           fecha_expedicion DATE,
                           persona_id BIGINT,
                           CONSTRAINT fk_persona FOREIGN KEY (persona_id) REFERENCES persona(id)
);

INSERT INTO persona (nombre)
VALUES
    ('Persona 1'), ('Persona 2'), ('Persona 3'), ('Persona 4'), ('Persona 5'),
    ('Persona 6'), ('Persona 7'), ('Persona 8'), ('Persona 9'), ('Persona 10'),
    ('Persona 11'), ('Persona 12'), ('Persona 13'), ('Persona 14'), ('Persona 15'),
    ('Persona 16'), ('Persona 17'), ('Persona 18'), ('Persona 19'), ('Persona 20'),
    ('Persona 21'), ('Persona 22'), ('Persona 23'), ('Persona 24'), ('Persona 25'),
    ('Persona 26'), ('Persona 27'), ('Persona 28'), ('Persona 29'), ('Persona 30'),
    ('Persona 31'), ('Persona 32'), ('Persona 33'), ('Persona 34'), ('Persona 35'),
    ('Persona 36'), ('Persona 37'), ('Persona 38'), ('Persona 39'), ('Persona 40'),
    ('Persona 41'), ('Persona 42'), ('Persona 43'), ('Persona 44'), ('Persona 45'),
    ('Persona 46'), ('Persona 47'), ('Persona 48'), ('Persona 49'), ('Persona 50'),
    ('Persona 51'), ('Persona 52'), ('Persona 53'), ('Persona 54'), ('Persona 55'),
    ('Persona 56'), ('Persona 57'), ('Persona 58'), ('Persona 59'), ('Persona 60'),
    ('Persona 61'), ('Persona 62'), ('Persona 63'), ('Persona 64'), ('Persona 65'),
    ('Persona 66'), ('Persona 67'), ('Persona 68'), ('Persona 69'), ('Persona 70'),
    ('Persona 71'), ('Persona 72'), ('Persona 73'), ('Persona 74'), ('Persona 75'),
    ('Persona 76'), ('Persona 77'), ('Persona 78'), ('Persona 79'), ('Persona 80'),
    ('Persona 81'), ('Persona 82'), ('Persona 83'), ('Persona 84'), ('Persona 85'),
    ('Persona 86'), ('Persona 87'), ('Persona 88'), ('Persona 89'), ('Persona 90'),
    ('Persona 91'), ('Persona 92'), ('Persona 93'), ('Persona 94'), ('Persona 95'),
    ('Persona 96'), ('Persona 97'), ('Persona 98'), ('Persona 99'), ('Persona 100');


INSERT INTO documento (tipo, fecha_expedicion, persona_id)
VALUES
    ('DNI', CURDATE(), 1),
    ('PASAPORTE', CURDATE(), 2),
    ('CARNET_EXTRANJERIA', CURDATE(), 3),
    ('DNI', CURDATE(), 4),
    ('PASAPORTE', CURDATE(), 5),
    ('CARNET_EXTRANJERIA', CURDATE(), 6),
    ('DNI', CURDATE(), 7),
    ('PASAPORTE', CURDATE(), 8),
    ('CARNET_EXTRANJERIA', CURDATE(), 9),
    ('DNI', CURDATE(), 10),
    ('PASAPORTE', CURDATE(), 11),
    ('CARNET_EXTRANJERIA', CURDATE(), 12),
    ('DNI', CURDATE(), 13),
    ('PASAPORTE', CURDATE(), 14),
    ('CARNET_EXTRANJERIA', CURDATE(), 15),
    ('DNI', CURDATE(), 16),
    ('PASAPORTE', CURDATE(), 17),
    ('CARNET_EXTRANJERIA', CURDATE(), 18),
    ('DNI', CURDATE(), 19),
    ('PASAPORTE', CURDATE(), 20),
    ('CARNET_EXTRANJERIA', CURDATE(), 21),
    ('DNI', CURDATE(), 22),
    ('PASAPORTE', CURDATE(), 23),
    ('CARNET_EXTRANJERIA', CURDATE(), 24),
    ('DNI', CURDATE(), 25),
    ('PASAPORTE', CURDATE(), 26),
    ('CARNET_EXTRANJERIA', CURDATE(), 27),
    ('DNI', CURDATE(), 28),
    ('PASAPORTE', CURDATE(), 29),
    ('CARNET_EXTRANJERIA', CURDATE(), 30),
    ('DNI', CURDATE(), 31),
    ('PASAPORTE', CURDATE(), 32),
    ('CARNET_EXTRANJERIA', CURDATE(), 33),
    ('DNI', CURDATE(), 34),
    ('PASAPORTE', CURDATE(), 35),
    ('CARNET_EXTRANJERIA', CURDATE(), 36),
    ('DNI', CURDATE(), 37),
    ('PASAPORTE', CURDATE(), 38),
    ('CARNET_EXTRANJERIA', CURDATE(), 39),
    ('DNI', CURDATE(), 40),
    ('PASAPORTE', CURDATE(), 41),
    ('CARNET_EXTRANJERIA', CURDATE(), 42),
    ('DNI', CURDATE(), 43),
    ('PASAPORTE', CURDATE(), 44),
    ('CARNET_EXTRANJERIA', CURDATE(), 45),
    ('DNI', CURDATE(), 46),
    ('PASAPORTE', CURDATE(), 47),
    ('CARNET_EXTRANJERIA', CURDATE(), 48),
    ('DNI', CURDATE(), 49),
    ('PASAPORTE', CURDATE(), 50),
    ('CARNET_EXTRANJERIA', CURDATE(), 51),
    ('DNI', CURDATE(), 52),
    ('PASAPORTE', CURDATE(), 53),
    ('CARNET_EXTRANJERIA', CURDATE(), 54),
    ('DNI', CURDATE(), 55),
    ('PASAPORTE', CURDATE(), 56),
    ('CARNET_EXTRANJERIA', CURDATE(), 57),
    ('DNI', CURDATE(), 58),
    ('PASAPORTE', CURDATE(), 59),
    ('CARNET_EXTRANJERIA', CURDATE(), 60),
    ('DNI', CURDATE(), 61),
    ('PASAPORTE', CURDATE(), 62),
    ('CARNET_EXTRANJERIA', CURDATE(), 63),
    ('DNI', CURDATE(), 64),
    ('PASAPORTE', CURDATE(), 65),
    ('CARNET_EXTRANJERIA', CURDATE(), 66),
    ('DNI', CURDATE(), 67),
    ('PASAPORTE', CURDATE(), 68),
    ('CARNET_EXTRANJERIA', CURDATE(), 69),
    ('DNI', CURDATE(), 70),
    ('PASAPORTE', CURDATE(), 71),
    ('CARNET_EXTRANJERIA', CURDATE(), 72),
    ('DNI', CURDATE(), 73),
    ('PASAPORTE', CURDATE(), 74),
    ('CARNET_EXTRANJERIA', CURDATE(), 75),
    ('DNI', CURDATE(), 76),
    ('PASAPORTE', CURDATE(), 77),
    ('CARNET_EXTRANJERIA', CURDATE(), 78),
    ('DNI', CURDATE(), 79),
    ('PASAPORTE', CURDATE(), 80),
    ('CARNET_EXTRANJERIA', CURDATE(), 81),
    ('DNI', CURDATE(), 82),
    ('PASAPORTE', CURDATE(), 83),
    ('CARNET_EXTRANJERIA', CURDATE(), 84),
    ('DNI', CURDATE(), 85),
    ('PASAPORTE', CURDATE(), 86),
    ('CARNET_EXTRANJERIA', CURDATE(), 87),
    ('DNI', CURDATE(), 88),
    ('PASAPORTE', CURDATE(), 89),
    ('CARNET_EXTRANJERIA', CURDATE(), 90),
    ('DNI', CURDATE(), 91),
    ('PASAPORTE', CURDATE(), 92),
    ('CARNET_EXTRANJERIA', CURDATE(), 93),
    ('DNI', CURDATE(), 94),
    ('PASAPORTE', CURDATE(), 95),
    ('CARNET_EXTRANJERIA', CURDATE(), 96),
    ('DNI', CURDATE(), 97),
    ('PASAPORTE', CURDATE(), 98),
    ('CARNET_EXTRANJERIA', CURDATE(), 99),
    ('DNI', CURDATE(), 100);
